### ISSUE TITLE
HTTP response 403: "403 Forbidden" Error

### ISSUE THREAD

**Issue by drkui** [vfauth/kickstarter-reward-notifier#3]
I'm getting this when I try running the example command with my own token and user ID:

```
2022/10/11 15:28:39 Could not get the project description, got HTTP response 403: "403 Forbidden"
exit status 1
```

I initially tried running the command with the Telegram options, but to narrow down if it was related to Telegram or not, this is the command I'm running:

`go run main.go "https://www.kickstarter.com/projects/gameops/emergency-operator-board-game" -i 0m10s`

**Comment by vfauth** [comment]
Well, it seems like Kickstarter now blocks bots/parsers and my tool is identified as one. I will try to see if somebody can be done.
